version: '3'

services:
  app:
    build:
      context: .
      target: build
      args:
        VARIANT: '2.7'
        NODE_VERSION: '18'
        PG_MAJOR: '12'
        BUNDLER_VERSION: '2.1.4'
    image: app:1.0.0
    stdin_open: true
    tty: true
    volumes:
      - bundle:/usr/local/bundle
      - .:/workspace
    command: /bin/bash
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails-sidekiq
    ports:
      - "5432:5432"

volumes:
  bundle: